version: '3.9'

services:
  apphost:
    build:
      context: ./AppHost
    ports:
      - "5100:80"

  blazor:
    build:
      context: ./BlazorWebApp
    ports:
      - "5000:80"

  orderservice:
    build:
      context: ./OrderService
    ports:
      - "5001:80"

  productservice:
    build:
      context: ./ProductService
    ports:
      - "5002:80"

  paymentservice:
    build:
      context: ./PaymentService
    ports:
      - "5003:80"

  identityservice:
    build:
      context: ./IdentityService
    ports:
      - "5004:80"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blazor
      - orderservice
